Wait up to 10 seconds for rebuilding to start

diff --git a/RAID/recover_raid b/RAID/recover_raid
--- a/RAID/recover_raid
+++ b/RAID/recover_raid
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2020, 2023 NVI, Inc.
+# Copyright (c) 2020, 2023, 2025 NVI, Inc.
 #
 # This file is part of FSL11 Linux distribution.
 # (see http://github.com/nvi-inc/fsl11).
@@ -103,13 +103,18 @@ else
 	echo "Re-adding missing device(s) to RAID array $raid ... "
 	mdadm $raid --re-add missing
 fi
-sleep 1
 
 mdadm --detail $raid; echo
-if ! mdadm --detail $raid | grep -q ", recovering $"; then
-	echo "ERROR: RAID $raid failed to start rebuilding"
-	exit 1
-fi
+count=10;
+while [ $count -eq 10 ] || ! mdadm --detail $raid | grep -q ", recovering $"; do
+	if [ $count -le 0 ]; then
+		echo -e "\nERROR: RAID $raid failed to start rebuilding"
+		exit 1
+	fi
+	echo  -n -e "\rWaiting up to $count seconds for RAID $raid to start rebuilding ... "
+	sleep 1
+	count=$((count-1))
+done
 
 if [ "$PROGRESS_METER" -ne 0 ]; then
 	echo "(This may safely be interrupted with 'Control-C' if you don't want to wait)"
diff --git a/RAID/refresh_secondary b/RAID/refresh_secondary
--- a/RAID/refresh_secondary
+++ b/RAID/refresh_secondary
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2020-2021, 2023-2024 NVI, Inc.
+# Copyright (c) 2020-2021, 2023-2025 NVI, Inc.
 #
 # This file is part of FSL11 Linux distribution.
 # (see http://github.com/nvi-inc/fsl11).
@@ -246,7 +246,6 @@ fi
 echo "Adding \"Secondary\" disk /dev/"$SDB"2 to RAID array /dev/md0 ... "
 [ $DRY_RUN -eq 0 ] && mdadm --zero-superblock /dev/"$SDB"2 2> /dev/null	# will fail if disk is blank
 [ $DRY_RUN -eq 0 ] && mdadm /dev/md0 --add-spare /dev/"$SDB"2
-sleep 1
 echo "done."
 
 if [ $DRY_RUN -ne 0 ]; then
@@ -256,10 +255,16 @@ fi
 
 
 # Check that the RAID is now rebuilding ie. the addition succeeded
-if ! (mdadm --detail /dev/md0 | grep -q ", recovering $"); then
-	echo "ERROR: RAID /dev/md0 failed to start rebuilding"
-	exit 1
-fi
+count=10;
+while [ $count -eq 10 ] || ! mdadm --detail /dev/md0 | grep -q ", recovering $"; do
+	if [ $count -le 0 ]; then
+		echo -e "\nERROR: RAID /dev/md0 failed to start rebuilding"
+		exit 1
+	fi
+	echo  -n -e "\rWaiting up to $count seconds for RAID /dev/md0 to start rebuilding ... "
+	sleep 1
+	count=$((count-1))
+done
 
 # Now RAID is using both disks again, we delete the override interlock file
 rm -f $lockf
