Add check for FS running

diff --git a/RAID/rotation_shutdown b/RAID/rotation_shutdown
--- a/RAID/rotation_shutdown
+++ b/RAID/rotation_shutdown
@@ -22,14 +22,19 @@
 set -e
 
 usage() {
-	echo "Usage: $0 [-h][-p]"
+	echo "Usage: $0 [-F][-h][-p]"
+	echo -e "  \t-F\toverride the FS running preventing shutdown"
 	echo -e "  \t-h\tdisplay this help and exit"
 	echo -e "  \t-p\tdisplay progress meter if recovering (no shutdown)"
 }
 
 PROGRESS_METER=0
-while getopts "hp" arg; do
+OVERRIDE_FS=0
+while getopts "Fhp" arg; do
 	case $arg in
+		F)
+			OVERRIDE_FS=1
+			;;
 		p)
 			PROGRESS_METER=1
 			;;
@@ -69,6 +74,21 @@ if [ "$PROGRESS_METER" -ne 0 ]; then
 	echo "RAID not degraded and not recovering."
 	echo "You can try '$0' again without '-p'."
 	exit 0
+fi
+
+if test -f /usr2/fs/bin/lognm ; then
+	if [ "$(/usr2/fs/bin/lognm 2>/dev/null)" ] ; then
+		if [ "$OVERRIDE_FS" -ne 0 ]; then
+			echo "The FS running, but -F was used to force a shutdown."
+		else
+			echo "ERROR: The FS is running; won't shutdown. Override with -F (not recommended)."
+			exit 1
+		fi
+	else
+		echo "The FS is not running. Shutting down is not prevented."
+	fi
+else
+	echo "The FS does not appear to be installed. Shutting down is not prevented."
 fi
 
 echo "RAID not degraded and not recovering. SAFE to rotate disks. Shutting down ..."
