Start AUID backup from operational system

diff --git a/AUID/backup_usr2 b/AUID/backup_usr2
--- a/AUID/backup_usr2
+++ b/AUID/backup_usr2
@@ -18,14 +18,12 @@
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
+
 set -e
 
-cd /usr/local/sbin
-#
-cp -a /root/fsl11/RAID/enable_spare enable_spare
-chown root.root enable_spare
-chmod a+r,u+wx,go-wx enable_spare
-#
-cp -a /root/fsl11/RAID/disable_spare disable_spare
-chown root.root disable_spare
-chmod a+r,u+wx,go-wx disable_spare
+if [[ "$USER" =~ ^(oper|prog)$ ]]; then
+	echo "ERROR: Cannot use $(basename $0) from $USER account. Try from $SUDO_USER."
+    exit 1
+fi
+
+sudo /usr/local/sbin/backup_usr2 "$@"
diff --git a/RAID/refresh_spare_usr2 b/RAID/refresh_spare_usr2
--- a/RAID/refresh_spare_usr2
+++ b/RAID/refresh_spare_usr2
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2020-2021, 2023 NVI, Inc.
+# Copyright (c) 2020-2021, 2023-2024 NVI, Inc.
 #
 # This file is part of FSL11 Linux distribution.
 # (see http://github.com/nvi-inc/fsl11).
@@ -231,8 +231,8 @@ if [[ -z "$subscript" ]]; then
 
         cat << EOF
 
-    IMPORTANT: It is best if no other sessions are logged in on this system and
-               no sessions should be logged in on the Operational system.
+    IMPORTANT: It is best if no other sessions are logged in on both the
+               Operational and Spare systems.
 
 EOF
 
@@ -245,8 +245,8 @@ EOF
             y|yes) echo -e "\nO.K. Continuing with refresh ... "
                    badans=false
                    ;;
-            n|no)  echo -e "\nO.K. Exiting."
-                   exit
+            n|no)  echo -e "\nO.K. Aborting."
+                   exit 1
                    ;;
             *)     echo -e "\nPlease answer with y=yes or n=no : \c"
           esac
@@ -270,10 +270,9 @@ exit 1
 #        D. Save the result.
 #   3. Follow the other directions in the 'Installing refresh_spare_usr2'
 #      subsection of the 'RAID Notes for FSL11' document.
-#      The CIS hardening approach may be a useful alternative, or necessary if
-#      you have a CIS hardened system.  For more information, see the
-#      'Installing refresh_spare_usr2 with CIS hardening' subsection of the
-#      'CIS Hardening for FSL11' document.
+#      For CIS hardened systems, follow the other directions in the 'Installing
+#      backup_usr2 for CIS hardening' section of the 'Additional items for FS
+#      operations' appendix of the 'CIS Hardening for FSL11' document.
 #   4. Test it the first time just after the Spare system's disk has been
 #      rotated.
 
