Trap account promoting from oper|prog for CIS
This prevents extraneous security messages.

diff --git a/AUID/oper_account b/AUID/oper_account
--- a/AUID/oper_account
+++ b/AUID/oper_account
@@ -20,6 +20,17 @@
 #
 
 set -e
+
+if [[ "$USER" =~ ^(prog)$ ]]; then
+  echo "ERROR: Cannot promote to oper from $USER account. Promote from $SUDO_USER instead."
+  exit 1
+else
+  if [[ "$USER" =~ ^oper$ ]]; then
+    echo "ERROR: Already in $USER account."
+    exit 1
+  fi
+fi
+
 if echo $DISPLAY |grep -q localhost; then
   sudo -u oper XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
 else
diff --git a/AUID/prog_account b/AUID/prog_account
--- a/AUID/prog_account
+++ b/AUID/prog_account
@@ -20,6 +20,17 @@
 #
 
 set -e
+
+if [[ "$USER" =~ ^(oper)$ ]]; then
+  echo "ERROR: Cannot promote to prog from $USER account. Promote from $SUDO_USER instead."
+  exit 1
+else
+  if [[ "$USER" =~ ^prog$ ]]; then
+    echo "ERROR: Already in $USER account."
+    exit 1
+  fi
+fi
+
 if echo $DISPLAY |grep -q localhost; then
   sudo -u prog XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
 else
diff --git a/AUID/root_account b/AUID/root_account
--- a/AUID/root_account
+++ b/AUID/root_account
@@ -20,6 +20,12 @@
 #
 
 set -e
+
+if [[ "$USER" =~ ^(oper|prog)$ ]]; then
+  echo "ERROR: Cannot promote to root from $USER account. Promote from $SUDO_USER instead."
+  exit 1
+fi
+
 if echo $DISPLAY |grep -q localhost; then
   sudo -u root XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
 else
